[[tasks]]
type = "ping"
schedule_seconds = 5
host = "8.8.8.8"
name = "Google DNS Ping"
timeout = 2


[[tasks]]
type = "ping"
schedule_seconds = 5
host = "1.1.1.1"
name = "Cloudfare DNS Ping"
timeout = 2


[[tasks]]
type = "ping"
schedule_seconds = 5
host = "9.9.9.9"
name = "Quad9 DNS Ping"
timeout = 2

[[tasks]]
type = "ping"
schedule_seconds = 5
host = "192.0.43.10"
name = "Example.com Ping"
timeout = 2

[[tasks]]
type = "ping"
schedule_seconds = 5
host = "4.2.2.1"
name = "4.2.2.1 DNS Ping"
timeout = 2

[[tasks]]
type = "ping"
schedule_seconds = 5
host = "208.67.222.222"
name = "Open DNS DNS Ping"
timeout = 2


[[tasks]]
type = "http_get"
schedule_seconds = 12
url = "https://www.sycope.com/"
name = "sycope health check"


[[tasks]]
type = "http_get"
schedule_seconds = 12
url = "https://cert.pl/"
name = "CERT health check"


[[tasks]]
type = "http_get"
schedule_seconds = 12
url = "https://www.amazon.pl/"
name = "amazon  health check"

[[tasks]]
type = "http_get"
schedule_seconds = 12
url = "https://www.gazeta.pl/0,0.html"
name = "gazeta health check"

[[tasks]]
type = "http_get"
schedule_seconds = 12
url = "https://www.wp.pl/"
name = "wp  health check"

[[tasks]]
type = "http_get"
schedule_seconds = 12
url = "https://duckduckgo.com/"
name = "duckduck  health check"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 6
# url = "https://www.reddit.com/"
# name = "reddit  health check"

[[tasks]]
type = "http_get"
schedule_seconds = 12
url = "https://www.google.pl/"
name = "google  health check"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 6
# url = "https://www.bbc.com/"
# name = "bbc  health check"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 6
# url = "https://www.interia.pl/"
# name = "interia  health check"



[[tasks]]
type = "dns_query"
schedule_seconds = 20
server = "1.1.1.1"
domain = "google.com"
record_type = "A"
name = "Cloudflare DNS A Record"
timeout = 3


# [[tasks]]
# type = "dns_query_doh"
# name = "DoH A Record Check"
# schedule_seconds = 30
# server_url = "https://cloudflare-dns.com/dns-query"
# domain = "google.com"
# record_type = "A"
# timeout_seconds = 5


[[tasks]]
type = "http_get"
schedule_seconds = 6
url = "https://lss.wilam.ovh/"
name = "Local http test / "


[[tasks]]
type = "http_get"
schedule_seconds = 6
url = "https://lss.wilam.ovh/sleep/1/"
name = "Local http test 1"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 6
# url = "https://lss.wilam.ovh/sleep/2/"
# name = "Local http test 2"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/3/"
# name = "Local http test 3"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/4/"
# name = "Local http test 4"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/5/"
# name = "Local http test 5"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/6/"
# name = "Local http test 6"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/7/"
# name = "Local http test 7"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/8/"
# name = "Local http test 8"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/9/"
# name = "Local http test 9"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/10/"
# name = "Local http test 10"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/11/"
# name = "Local http test 11"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/12/"
# name = "Local http test 12"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/13/"
# name = "Local http test 13"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/14/"
# name = "Local http test 14"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/15/"
# name = "Local http test 15"

[[tasks]]
type = "http_get"
schedule_seconds = 6
url = "https://lss.wilam.ovh/sleep/16/"
name = "Local http test 16"

[[tasks]]
type = "http_get"
schedule_seconds = 6
url = "https://lss.wilam.ovh/sleep/17/"
name = "Local http test 17"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 6
# url = "https://lss.wilam.ovh/sleep/18/"
# name = "Local http test 18"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 6
# url = "https://lss.wilam.ovh/sleep/19/"
# name = "Local http test 19"

# [[tasks]]
# type = "http_get"
# schedule_seconds = 6
# url = "https://lss.wilam.ovh/sleep/20/"
# name = "Local http test 20"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/100/"
# name = "Local http test 100"


[[tasks]]
type = "http_get"
schedule_seconds = 1
url = "https://lss.wilam.ovh/sleep/200/"
name = "Local http test 200"



# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/300/"
# name = "Local http test 300"



# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/400/"
# name = "Local http test 400"



# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/500/"
# name = "Local http test 500"



# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/600/"
# name = "Local http test 600"



# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/700/"
# name = "Local http test 700"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/800/"
# name = "Local http test 800"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/900/"
# name = "Local http test 900"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/1000/"
# name = "Local http test 1000"


[[tasks]]
type = "http_get"
schedule_seconds = 1
url = "https://lss.wilam.ovh/sleep/1100/"
name = "Local http test 1100"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/1200/"
# name = "Local http test 1200"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/1300/"
# name = "Local http test 1300"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/1400/"
# name = "Local http test 1400"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 1
# url = "https://lss.wilam.ovh/sleep/1500/"
# name = "Local http test 1500"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 2
# url = "https://lss.wilam.ovh/sleep/1600/"
# name = "Local http test 1600"


[[tasks]]
type = "http_get"
schedule_seconds = 2
url = "https://lss.wilam.ovh/sleep/1700/"
name = "Local http test 1700"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 2
# url = "https://lss.wilam.ovh/sleep/1800/"
# name = "Local http test 1800"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 2
# url = "https://lss.wilam.ovh/sleep/1900/"
# name = "Local http test 1900"


# [[tasks]]
# type = "http_get"
# schedule_seconds = 3
# url = "https://lss.wilam.ovh/sleep/2000/"
# name = "Local http test 2000"


[[tasks]]
type = "http_get"
name = "lss true"
schedule_seconds = 5
url = "https://lss.wilam.ovh/sleep/100/"
timeout_seconds = 15           # HTTP request timeout (default: 30s)
verify_ssl = true              # Enforce valid SSL certificate (default: false)


[[tasks]]
type = "http_get"
name = "lss false"
schedule_seconds = 5
url = "https://lss.wilam.ovh/sleep/100/"
timeout_seconds = 15           # HTTP request timeout (default: 30s)
verify_ssl = false              # Enforce valid SSL certificate (default: false)


[[tasks]]
type = "http_get"
name = "lss-unsigned true"
schedule_seconds = 5
url = "http://lss-unsecured.wilam.ovh/sleep/100/"
timeout_seconds = 15           # HTTP request timeout (default: 30s)
verify_ssl = true              # Enforce valid SSL certificate (default: false)


[[tasks]]
type = "http_get"
name = "lss-unsigned false"
schedule_seconds = 5
url = "http://lss-unsecured.wilam.ovh/sleep/100/"
timeout_seconds = 15           # HTTP request timeout (default: 30s)
verify_ssl = false              # Enforce valid SSL certificate (default: false)

[[tasks]]
type = "http_get"
name = "lss-selfsigned true"
schedule_seconds = 5
url = "https://lss-selfsigned.wilam.ovh/sleep/100/"
timeout_seconds = 15           # HTTP request timeout (default: 30s)
verify_ssl = true              # Enforce valid SSL certificate (default: false)


[[tasks]]
type = "http_get"
name = "lss-selfsigned false"
schedule_seconds = 5
url = "https://lss-selfsigned.wilam.ovh/sleep/100/"
timeout_seconds = 15           # HTTP request timeout (default: 30s)
verify_ssl = false              # Enforce valid SSL certificate (default: false)

[[tasks]]
type = "http_get"
name = "httpforever false"
schedule_seconds = 12
url = "http://httpforever.com/"
timeout_seconds = 15           # HTTP request timeout (default: 30s)
verify_ssl = false              # Enforce valid SSL certificate (default: false)


[[tasks]]
type = "bandwidth"
name = "wmd"
schedule_seconds = 60           # Minimum allowed
timeout_seconds = 30


[[tasks]]
type = "http_content"
name = "wilam random a b"
schedule_seconds = 2
url = "https://lss.wilam.ovh/random_a_b"
regexp = "AAA_WORKING_AAA"
timeout_seconds = 15
