# Network Monitoring Central Server Configuration

listen_address = "0.0.0.0:8787"
api_key = "N33dekwKfEC5meM78uyqoAmuJuAkbRCQYJF"
data_retention_days = 30
agent_configs_dir = "/linksense_server/agent-configs"
bandwidth_test_size_mb = 10

# Reconfiguration settings (optional, defaults shown)
# reconfigure_check_interval_seconds = 10   # How often to check for config updates (min: 1, max: 300)

# Cleanup settings (optional, defaults shown)
# cleanup_interval_hours = 24               # Database cleanup interval
# initial_cleanup_delay_seconds = 3600      # Initial delay before first cleanup (1 hour)

# Rate limiting (optional, defaults shown)
# rate_limit_enabled = true
# rate_limit_window_seconds = 60
# rate_limit_max_requests = 100

# Bandwidth test management (optional, defaults shown)
# bandwidth_test_timeout_seconds = 120                      # Bandwidth test timeout (2 minutes)
# bandwidth_queue_base_delay_seconds = 30                   # Base delay when no test running
# bandwidth_queue_current_test_delay_seconds = 60           # Delay for current test (1 minute)
# bandwidth_queue_position_multiplier_seconds = 30          # Delay multiplier per queue position
# bandwidth_max_delay_seconds = 300                         # Maximum delay suggestion (5 minutes)

# Shutdown behavior (optional, defaults shown)
# graceful_shutdown_timeout_seconds = 30    # Wait time for background tasks during shutdown

# Optional: Whitelist of allowed agent IDs (empty = all agents allowed)
# agent_id_whitelist = []
